In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import pandas as pd
import numpy as _np
from apollon.datasets import load_earthquakes

In [4]:
from apollon.hmm.poisson_hmm import PoissonHmm


In [5]:
import warnings
warnings.filterwarnings('default')

In [6]:
def params(x, m, mv):
    lam = np.linspace(x.min(), x.max(), m, endpoint=True)
    gam = np.empty((m, m))
    gam.fill((1-mv) / (m-1))
    fill_diagonal(gam, mv)
    delta = np.repeat(1/m, m)
    return (lam, gam, delta)

In [7]:
m = 3
x = load_earthquakes().data
l, g, d = params(x, m, .8)
theta = l, g, d

In [8]:
mod = PoissonHmm(x,m)

In [9]:
mod.fit_EM()

In [10]:

mod.gamma_

array([[9.39293877e-01, 3.20984856e-02, 2.86076377e-02],
       [4.04017229e-02, 9.06436067e-01, 5.31622103e-02],
       [3.69867511e-21, 1.90255941e-01, 8.09744059e-01]])

In [11]:
mod.nice

<bound method PoissonHmm.nice of Lambda
[13.1338 19.7132 29.7097]

Delta
[0.3254 0.489  0.1856]

Gamma
[[0.9393 0.0321 0.0286]
 [0.0404 0.9064 0.0532]
 [0.     0.1903 0.8097]]

Mllk           AIC            BIC            
-328.5275      687.055        727.1474       >

In [19]:
log1p(-.1)

-0.10536051565782631